apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawmaze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drawmaze
  template:
    metadata:
      labels:
        app: drawmaze
    spec:
      containers:
      - name: drawmaze
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: contents
      volumes:
      - persistentVolumeClaim:
          claimName: drawmaze
        name: contents
