apiVersion: v1
kind: Service
metadata:
  name: drawmaze
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: drawmaze
  sessionAffinity: None
  type: ClusterIP
